name: Build Plugin
on: [ push ]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradleVersion: ["6.6.1", "6.9.4", "7.0.2", "7.6.4", "8.0.2"]
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 11
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - run: "./gradlew test${{ gradleVersion }}"
